- lineinfile:
    path: /etc/ntp.conf 
    regexp: "server 0.debian.pool.ntp.org iburst"
    line: "#server 0.debian.pool.ntp.org iburst"
  notify: restart ntp
- lineinfile:
    path: /etc/ntp.conf 
    regexp: "server 1.debian.pool.ntp.org iburst"
    line: "#server 1.debian.pool.ntp.org iburst"
  notify: restart ntp
- lineinfile:
    path: /etc/ntp.conf 
    regexp: "server 2.debian.pool.ntp.org iburst"
    line: "#server 2.debian.pool.ntp.org iburst"
  notify: restart ntp
- lineinfile:
    path: /etc/ntp.conf 
    regexp: "server 3.debian.pool.ntp.org iburst"
    line: "#server 3.debian.pool.ntp.org iburst"
  notify: restart ntp
- lineinfile: 
    path: /etc/ntp.conf 
    insertafter: '^#server 3.debian.pool.ntp.org iburst'
    line: "pool ntp.nict.jp iburst"
  notify: restart ntp
