- lineinfile: dest=/etc/dhcpcd.conf regexp="^interface " line="interface {{ static_ip.interface }}"
  notify: reboot os
- lineinfile: dest=/etc/dhcpcd.conf regexp="^static ip_address=" line="static ip_address={{ static_ip.ip_address }}"
  notify: reboot os
- lineinfile: dest=/etc/dhcpcd.conf regexp="^static routers=" line="static routers={{ static_ip.routers }}"
  notify: reboot os
- lineinfile: dest=/etc/dhcpcd.conf regexp="^static domain_name_servers=" line="static domain_name_servers={{ static_ip.domain_name_servers }}"
  notify: reboot os
- sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present
    reload: no
  notify: reboot os
