- file: path=/srv/capture state=directory owner=root group=root mode=0755
- copy: src=srv/capture/capture.sh dest=/srv/capture/capture.sh owner=root group=root mode=0755
  notify: restart capture
- copy: src=srv/capture/capture.conf dest=/srv/capture/capture.conf owner=root group=root mode=0644
  notify: restart capture
- copy: src=etc/systemd/system/capture.service dest=/etc/systemd/system/capture.service owner=root group=root mode=0755
  notify: restart capture
- systemd: name=capture enabled=yes
