- name: config server image
  hosts: all
  become: yes
  roles:
    - ntp
    - timezone
    - git
    - tshark
    - python-pip
    - pyyaml
    - requests
    - mon-if
    - { role: capture, tags: [ 'capture' ] }
    - { role: zabbix-agent, tags: [ 'zabbix-agent' ] }
    - { role: post_data, tags: [ 'post_data' ] }
    - { role: static_ip, tags: [ 'static_ip' ] }
