- name: config server image
  hosts: all
  become: yes
  roles:
    - ntp
    - timezone
    - git
    - zabbix-agent
    - tshark
    - python-pip
    - pyyaml
    - requests
    - mon-if
    - capture
    - post_data
    - { role: static_ip, tags: [ 'static_ip' ] }
