- name: config server image
  hosts: all
  become: yes
  roles:
    - timezone
    - git
    - zabbix-agent
    - tshark
    - python-pip
    - pyyaml
    - requests
    - grequests
    - mon-if
    - capture
    - post_data
