- name: config server image
  hosts: all
  become: yes
  roles:
    - swap
    - rsyslog
    - tmpfs
    - logrotate
    - man-db
    - python-apt
    - mon-if
    - tshark
    - pyyaml
    - { role: capture, tags: [ 'capture' ] }
    - { role: post_data, tags: [ 'post_data' ] }

