- apt:
    name: zabbix-agent
- lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server="
    line: "Server={{ zabbix_agent.server_hostname }}"
  notify: restart zabbix-agent
- lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive"
    line: "ServerActive={{ zabbix_agent.server_hostname }}"
  notify: restart zabbix-agent
- lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Hostname="
    line: "Hostname={{ ansible_hostname }}"
  notify: restart zabbix-agent
- lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: "^HostnameItem="
    line: "HostnameItem={{ ansible_hostname }}"
  notify: restart zabbix-agent
- lineinfile:
    dest: /etc/hosts
    regexp: "{{ zabbix_agent.server_hostname }}$"
    line: "{{ zabbix_agent.server_ip_address }}\t{{ zabbix_agent.server_hostname }}"
  notify: restart zabbix-agent
