- file: path=/srv/mon-if state=directory owner=root group=root mode=0755
- copy: src=srv/mon-if/mon-if.sh dest=/srv/mon-if/mon-if.sh owner=root group=root mode=0700
  notify: mon-if up
- copy: src=etc/systemd/system/mon-if.service dest=/etc/systemd/system/mon-if.service owner=root group=root mode=0644
  notify: mon-if up
